<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\AppMenu;
use DB;

class AppMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection('dbcentral')->table('tb_menu')->insert([            
            // ['menu_id'=>'AA000','group_menu'=>'pengaturan','menu_title'=>'Pengaturan','no_urut'=>'AA000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'cog','menu_link'=>'' ],
            // ['menu_id'=>'AA001','group_menu'=>'pengaturan','menu_title'=>'Role Pengguna','no_urut'=>'AA001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pengaturan/role' ],
            // ['menu_id'=>'AA002','group_menu'=>'pengaturan','menu_title'=>'Manajemen Pengguna','no_urut'=>'AA002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pengaturan/pengguna' ],
            // ['menu_id'=>'AA003','group_menu'=>'pengaturan','menu_title'=>'Parameter Sistem','no_urut'=>'AA003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pengaturan/parameter' ],
            // ['menu_id'=>'AA004','group_menu'=>'pengaturan','menu_title'=>'Tempat Kerja','no_urut'=>'AA004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pengaturan/tempatkerja' ],

            // ['menu_id'=>'BB000','group_menu'=>'masterdata','menu_title'=>'Master Data','no_urut'=>'BB000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'database','menu_link'=>'' ],
            // ['menu_id'=>'BB001','group_menu'=>'masterdata','menu_title'=>'Referensi Aplikasi','no_urut'=>'BB001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/referensi' ],
            // ['menu_id'=>'BB002','group_menu'=>'masterdata','menu_title'=>'COA - Code Of Accounts','no_urut'=>'BB002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/coa' ],
            // ['menu_id'=>'BB003','group_menu'=>'masterdata','menu_title'=>'Asuransi dan Penjamin','no_urut'=>'BB003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/asuransi' ],
            // ['menu_id'=>'BB004','group_menu'=>'masterdata','menu_title'=>'Pemasok dan Pabrikan','no_urut'=>'BB004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/pemasok' ],
            // ['menu_id'=>'BB005','group_menu'=>'masterdata','menu_title'=>'Kelompok Tagihan','no_urut'=>'BB005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/tagihan' ],
            // ['menu_id'=>'BB006','group_menu'=>'masterdata','menu_title'=>'Kelompok Vklaim','no_urut'=>'BB006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/vklaim' ],
            // ['menu_id'=>'BB007','group_menu'=>'masterdata','menu_title'=>'Komponen Harga','no_urut'=>'BB007','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/komponen/tariff' ],
            // ['menu_id'=>'BB008','group_menu'=>'masterdata','menu_title'=>'Kelompok Tindakan','no_urut'=>'BB008','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/tindakan' ],
            // ['menu_id'=>'BB009','group_menu'=>'masterdata','menu_title'=>'Tindakan dan pemeriksaan','no_urut'=>'BB009','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/tindakan' ],
            // ['menu_id'=>'BB010','group_menu'=>'masterdata','menu_title'=>'Kode Laporan RL','no_urut'=>'BB010','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/rl' ],
            // ['menu_id'=>'BB011','group_menu'=>'masterdata','menu_title'=>'Wilayah','no_urut'=>'BB011','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/wilayah' ],
            // ['menu_id'=>'BB012','group_menu'=>'masterdata','menu_title'=>'Kode ICD','no_urut'=>'BB012','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/icd' ],
            // ['menu_id'=>'BB013','group_menu'=>'masterdata','menu_title'=>'DTD dan Diagnosa','no_urut'=>'BB013','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/dtd' ],
            // ['menu_id'=>'BB014','group_menu'=>'masterdata','menu_title'=>'Pasien','no_urut'=>'BB014','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/pasien' ],
            // ['menu_id'=>'BB015','group_menu'=>'masterdata','menu_title'=>'Referensi Produk','no_urut'=>'BB015','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/referensi/produk' ],
            // ['menu_id'=>'BB016','group_menu'=>'masterdata','menu_title'=>'Akun Produk','no_urut'=>'BB016','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/akun/produk' ],
            // ['menu_id'=>'BB017','group_menu'=>'masterdata','menu_title'=>'Signa Obat','no_urut'=>'BB017','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/signa' ],
            // ['menu_id'=>'BB018','group_menu'=>'masterdata','menu_title'=>'Item Medis','no_urut'=>'BB018','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/produk/medis' ],
            // ['menu_id'=>'BB019','group_menu'=>'masterdata','menu_title'=>'Item Non Medis ','no_urut'=>'BB019','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/produk/umum' ],
            // ['menu_id'=>'BB020','group_menu'=>'masterdata','menu_title'=>'Item Dapur','no_urut'=>'BB020','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/produk/dapur' ],
            // ['menu_id'=>'BB021','group_menu'=>'masterdata','menu_title'=>'Depo Persediaan','no_urut'=>'BB021','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/depo' ],
            // ['menu_id'=>'BB022','group_menu'=>'masterdata','menu_title'=>'KSM-Kelompok Staf Medis','no_urut'=>'BB022','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/ksm' ],
            // ['menu_id'=>'BB023','group_menu'=>'masterdata','menu_title'=>'Spesialisasi Dokter','no_urut'=>'BB023','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/spesialisasi' ],
            // ['menu_id'=>'BB024','group_menu'=>'masterdata','menu_title'=>'Dokter dan Spesialis','no_urut'=>'BB024','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/dokter' ],
            // ['menu_id'=>'BB025','group_menu'=>'masterdata','menu_title'=>'Kelas Pelayanan','no_urut'=>'BB025','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelas' ],
            // ['menu_id'=>'BB026','group_menu'=>'masterdata','menu_title'=>'Unit Pelayanan','no_urut'=>'BB026','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/unit/pelayanan' ],
            // ['menu_id'=>'BB027','group_menu'=>'masterdata','menu_title'=>'Jadwal Praktek Dokter','no_urut'=>'BB027','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/jadwal/dokter' ],
            // ['menu_id'=>'BB028','group_menu'=>'masterdata','menu_title'=>'Template Hasil Radiologi','no_urut'=>'BB028','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/template/rad' ],
            // ['menu_id'=>'BB029','group_menu'=>'masterdata','menu_title'=>'Template Hasil Lab','no_urut'=>'BB029','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/template/lab' ],
            // ['menu_id'=>'BB030','group_menu'=>'masterdata','menu_title'=>'Item Hasil Laboratorium','no_urut'=>'BB030','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/itemlab' ],
            // ['menu_id'=>'BB031','group_menu'=>'masterdata','menu_title'=>'Makanan','no_urut'=>'BB031','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/makanan' ],
            // ['menu_id'=>'BB032','group_menu'=>'masterdata','menu_title'=>'Diet Pasien','no_urut'=>'BB032','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/diet' ],
            // ['menu_id'=>'BB033','group_menu'=>'masterdata','menu_title'=>'Kelompok Makanan','no_urut'=>'BB033','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/makanan' ],
            // ['menu_id'=>'BB034','group_menu'=>'masterdata','menu_title'=>'Menu','no_urut'=>'BB034','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/menu' ],
            // ['menu_id'=>'BB035','group_menu'=>'masterdata','menu_title'=>'Menu Makanan','no_urut'=>'BB035','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/mealsmenu' ],
            // ['menu_id'=>'BB036','group_menu'=>'masterdata','menu_title'=>'Kelompok Menu','no_urut'=>'BB036','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/menu' ],
            // ['menu_id'=>'BB037','group_menu'=>'masterdata','menu_title'=>'Template Gizi','no_urut'=>'BB037','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/template/gizi' ],
            // ['menu_id'=>'BB038','group_menu'=>'masterdata','menu_title'=>'Distribusi Gizi','no_urut'=>'BB038','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/distribusi/gizi' ],
            // ['menu_id'=>'BB039','group_menu'=>'masterdata','menu_title'=>'Detail Distribusi Gizi','no_urut'=>'BB039','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/distribusi/detail/gizi' ],
            // ['menu_id'=>'BB040','group_menu'=>'masterdata','menu_title'=>'Kelompok Harga','no_urut'=>'BB040','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/harga' ],
            // ['menu_id'=>'BB041','group_menu'=>'masterdata','menu_title'=>'Ruang dan Bed','no_urut'=>'BB041','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/ruang' ],

            // ['menu_id'=>'CC000','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran','no_urut'=>'CC000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'album','menu_link'=>'' ],
            // ['menu_id'=>'CC001','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran Poli dan IGD','no_urut'=>'CC001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pendaftaran/poli' ],
            // ['menu_id'=>'CC002','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran Rawat Inap','no_urut'=>'CC002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pendaftaran/inap' ],
            // ['menu_id'=>'CC003','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran MCU','no_urut'=>'CC003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pendaftaran/mcu' ],
            // ['menu_id'=>'CC004','group_menu'=>'pendaftaran','menu_title'=>'Jadwal Operasi','no_urut'=>'CC004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pendaftaran/operasi' ],
            // ['menu_id'=>'CC005','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran Penunjang','no_urut'=>'CC005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pendaftaran/penunjang' ],

            // ['menu_id'=>'DD000','group_menu'=>'pelayanan','menu_title'=>'Pelayanan','no_urut'=>'DD000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'heart','menu_link'=>'' ],
            // ['menu_id'=>'DD001','group_menu'=>'pelayanan','menu_title'=>'Rawat Jalan','no_urut'=>'DD001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/poli' ],
            // ['menu_id'=>'DD002','group_menu'=>'pelayanan','menu_title'=>'IGD - Gawat Darurat','no_urut'=>'DD002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/igd' ],
            // ['menu_id'=>'DD003','group_menu'=>'pelayanan','menu_title'=>'Rawat Inap','no_urut'=>'DD003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/inap' ],
            // ['menu_id'=>'DD004','group_menu'=>'pelayanan','menu_title'=>'Bedah Sentral','no_urut'=>'DD004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/bedah' ],
            // ['menu_id'=>'DD005','group_menu'=>'pelayanan','menu_title'=>'Medical Check Up (MCU)','no_urut'=>'DD005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/mcu' ],
            // ['menu_id'=>'DD006','group_menu'=>'pelayanan','menu_title'=>'Asuhan Keperawatan','no_urut'=>'DD006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/keperawatan' ],

            // ['menu_id'=>'EE000','group_menu'=>'penunjang','menu_title'=>'Penunjang','no_urut'=>'EE000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'lifesaver','menu_link'=>'' ],
            // ['menu_id'=>'EE001','group_menu'=>'penunjang','menu_title'=>'Laboratorium','no_urut'=>'EE001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/lab' ],
            // ['menu_id'=>'EE002','group_menu'=>'penunjang','menu_title'=>'Radiologi','no_urut'=>'EE002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/rad' ],
            // ['menu_id'=>'EE003','group_menu'=>'penunjang','menu_title'=>'Hemodialisa','no_urut'=>'EE003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/hemo' ],
            // ['menu_id'=>'EE004','group_menu'=>'penunjang','menu_title'=>'Fisiotherapi','no_urut'=>'EE004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/fisio' ],
            // ['menu_id'=>'EE005','group_menu'=>'penunjang','menu_title'=>'Pathologi Anatomi','no_urut'=>'EE005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/patologi' ],
            // ['menu_id'=>'EE006','group_menu'=>'penunjang','menu_title'=>'Bank Darah','no_urut'=>'EE006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/bankdarah' ],
            // ['menu_id'=>'EE007','group_menu'=>'penunjang','menu_title'=>'Resep dan Obat','no_urut'=>'EE007','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/farmasi' ],
            // ['menu_id'=>'EE009','group_menu'=>'penunjang','menu_title'=>'Apotek','no_urut'=>'EE009','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/apotek' ],
            // ['menu_id'=>'EE010','group_menu'=>'penunjang','menu_title'=>'Ambulance','no_urut'=>'EE010','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/ambulance' ],
            // ['menu_id'=>'EE012','group_menu'=>'penunjang','menu_title'=>'Pemulasaraan Jenazah','no_urut'=>'EE012','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/pemulasaraan' ],
            // ['menu_id'=>'EE013','group_menu'=>'penunjang','menu_title'=>'Laundry','no_urut'=>'EE013','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/laundry' ],
            // ['menu_id'=>'EE014','group_menu'=>'penunjang','menu_title'=>'CSSD','no_urut'=>'EE014','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/cssd' ],
            // ['menu_id'=>'EE011','group_menu'=>'penunjang','menu_title'=>'Gizi dan Diet Pasien','no_urut'=>'EE011','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/gizi' ],

            // ['menu_id'=>'FF000','group_menu'=>'persediaan','menu_title'=>'Manajemen Persediaan','no_urut'=>'FF000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'tag','menu_link'=>'persediaan' ],
            // ['menu_id'=>'FF001','group_menu'=>'persediaan','menu_title'=>'Stock Opname','no_urut'=>'FF001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/opname' ],
            // ['menu_id'=>'FF002','group_menu'=>'persediaan','menu_title'=>'Stock Adjustment','no_urut'=>'FF002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/penyesuaian' ],
            // ['menu_id'=>'FF003','group_menu'=>'persediaan','menu_title'=>'Pengeluaran Persediaan','no_urut'=>'FF003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/pengeluaran' ],
            // ['menu_id'=>'FF004','group_menu'=>'persediaan','menu_title'=>'Produksi Persediaan','no_urut'=>'FF004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/produksi' ],
            // ['menu_id'=>'FF005','group_menu'=>'persediaan','menu_title'=>'Distribusi Persediaan','no_urut'=>'FF005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/distribusi' ],
            // ['menu_id'=>'FF006','group_menu'=>'persediaan','menu_title'=>'Purchase Request','no_urut'=>'FF006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/permintaan' ],
            // ['menu_id'=>'FF007','group_menu'=>'persediaan','menu_title'=>'Purchase Order','no_urut'=>'FF007','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/pembelian' ],
            // ['menu_id'=>'FF008','group_menu'=>'persediaan','menu_title'=>'PO Receive','no_urut'=>'FF008','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/penerimaan' ],
            // ['menu_id'=>'FF009','group_menu'=>'persediaan','menu_title'=>'PO Return','no_urut'=>'FF009','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/pengembalian' ],
            // ['menu_id'=>'FF010','group_menu'=>'persediaan','menu_title'=>'Penerimaan Hibah','no_urut'=>'FF010','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/hibah' ],
            // ['menu_id'=>'FF011','group_menu'=>'persediaan','menu_title'=>'Pembelian Langsung','no_urut'=>'FF011','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/belilangsung' ],
            // ['menu_id'=>'FF012','group_menu'=>'persediaan','menu_title'=>'Pengelolaan Pengadaan','no_urut'=>'FF012','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/maintenance' ],
            // ['menu_id'=>'FF013','group_menu'=>'persediaan','menu_title'=>'Pemusnahan','no_urut'=>'FF013','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/pemusnahan' ],
            
            // // SatuSehat Menu
            // ['menu_id'=>'GG000','group_menu'=>'satusehat','menu_title'=>'SatuSehat','no_urut'=>'GG000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'album','menu_link'=>'/satusehat' ],
            // ['menu_id'=>'GG001','group_menu'=>'satusehat','menu_title'=>'Practitioner Reference','no_urut'=>'GG001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/satusehat/practitioner' ],
            // ['menu_id'=>'GG002','group_menu'=>'satusehat','menu_title'=>'Patient Reference','no_urut'=>'GG002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/satusehat/patient' ],
            // ['menu_id'=>'GG003','group_menu'=>'satusehat','menu_title'=>'Organization','no_urut'=>'GG003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/satusehat/organization' ],
        
            ['menu_id'=>'AA000','group_menu'=>'pengaturan','menu_title'=>'Pengaturan','no_urut'=>'AA000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'cog','menu_link'=>'pengaturan' ],
            ['menu_id'=>'AA001','group_menu'=>'pengaturan','menu_title'=>'Role Pengguna','no_urut'=>'AA001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pengaturan/role' ],
            ['menu_id'=>'AA002','group_menu'=>'pengaturan','menu_title'=>'Manajemen Pengguna','no_urut'=>'AA002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pengaturan/pengguna' ],
            ['menu_id'=>'AA003','group_menu'=>'pengaturan','menu_title'=>'Parameter Sistem','no_urut'=>'AA003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pengaturan/parameter' ],
            ['menu_id'=>'AA004','group_menu'=>'pengaturan','menu_title'=>'Tempat Kerja','no_urut'=>'AA004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pengaturan/tempatkerja' ],
            ['menu_id'=>'AA005','group_menu'=>'pengaturan','menu_title'=>'Template Master Data','no_urut'=>'AA005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pengaturan/templatemaster' ],
            
            ['menu_id'=>'BB000','group_menu'=>'accounting','menu_title'=>'Acc & Keuangan','no_urut'=>'BB000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'tag','menu_link'=>'accounting' ],
            ['menu_id'=>'BB001','group_menu'=>'accounting','menu_title'=>'Referensi','no_urut'=>'BB001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/referensi/keuangan' ],
            ['menu_id'=>'BB002','group_menu'=>'accounting','menu_title'=>'COA - Code Of Account','no_urut'=>'BB002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/coa' ],
            ['menu_id'=>'BB003','group_menu'=>'accounting','menu_title'=>'Komponen Harga','no_urut'=>'BB003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/komponen/tariff' ],
            ['menu_id'=>'BB004','group_menu'=>'accounting','menu_title'=>'Akun Produk','no_urut'=>'BB004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/akun/produk' ],
            ['menu_id'=>'BB005','group_menu'=>'accounting','menu_title'=>'Kelompok Tagihan Pasien','no_urut'=>'BB005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/tagihan' ],
            ['menu_id'=>'BB006','group_menu'=>'accounting','menu_title'=>'Kelompok V-claim','no_urut'=>'BB006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/vklaim' ],
            ['menu_id'=>'BB007','group_menu'=>'accounting','menu_title'=>'Item Pelayanan','no_urut'=>'BB007','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/tindakan' ],
            ['menu_id'=>'BB008','group_menu'=>'accounting','menu_title'=>'Master Cara Bayar','no_urut'=>'BB008','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/cara/bayar' ],
            ['menu_id'=>'BB009','group_menu'=>'accounting','menu_title'=>'Kelompok Harga','no_urut'=>'BB009','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/kelompok/harga' ],
            ['menu_id'=>'BB010','group_menu'=>'accounting','menu_title'=>'Master Harga Pelayanan','no_urut'=>'BB010','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/harga' ],
            ['menu_id'=>'BB011','group_menu'=>'accounting','menu_title'=>'Penjamin dan Asuransi','no_urut'=>'BB011','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/asuransi' ],

            ['menu_id'=>'CC000','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran','no_urut'=>'CC000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'album','menu_link'=>'Pendaftaran' ],
            ['menu_id'=>'CC001','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran Poli dan IGD','no_urut'=>'CC001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pendaftaran/poli' ],
            ['menu_id'=>'CC002','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran Rawat Inap','no_urut'=>'CC002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pendaftaran/inap' ],
            ['menu_id'=>'CC003','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran MCU','no_urut'=>'CC003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pendaftaran/mcu' ],
            ['menu_id'=>'CC004','group_menu'=>'pendaftaran','menu_title'=>'Jadwal Operasi','no_urut'=>'CC004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pendaftaran/operasi' ],
            ['menu_id'=>'CC005','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran Laboratorium','no_urut'=>'CC005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/lab/registrasi' ],
            ['menu_id'=>'CC006','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran Radiologi','no_urut'=>'CC006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/rad/registrasi' ],
            ['menu_id'=>'CC007','group_menu'=>'pendaftaran','menu_title'=>'Pendaftaran Penunjang','no_urut'=>'CC007','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pendaftaran/penunjang' ],

            ['menu_id'=>'DD000','group_menu'=>'pelayanan','menu_title'=>'Pelayanan','no_urut'=>'DD000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'heart','menu_link'=>'pelayanan' ],
            ['menu_id'=>'DD001','group_menu'=>'pelayanan','menu_title'=>'Rawat Jalan','no_urut'=>'DD001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/poli' ],
            ['menu_id'=>'DD002','group_menu'=>'pelayanan','menu_title'=>'IGD - Gawat Darurat','no_urut'=>'DD002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/igd' ],
            ['menu_id'=>'DD003','group_menu'=>'pelayanan','menu_title'=>'Rawat Inap','no_urut'=>'DD003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/inap' ],
            ['menu_id'=>'DD004','group_menu'=>'pelayanan','menu_title'=>'Bedah Sentral','no_urut'=>'DD004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/bedah' ],
            ['menu_id'=>'DD005','group_menu'=>'pelayanan','menu_title'=>'Medical Check Up (MCU)','no_urut'=>'DD005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/mcu' ],
            ['menu_id'=>'DD006','group_menu'=>'pelayanan','menu_title'=>'Asuhan Keperawatan','no_urut'=>'DD006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pelayanan/keperawatan' ],

            ['menu_id'=>'EE000','group_menu'=>'penunjang','menu_title'=>'Penunjang','no_urut'=>'EE000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'lifesaver','menu_link'=>'penunjang' ],
            ['menu_id'=>'EE001','group_menu'=>'penunjang','menu_title'=>'Resep dan Obat','no_urut'=>'EE001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/prescriptions' ],
            ['menu_id'=>'EE002','group_menu'=>'penunjang','menu_title'=>'Apotek','no_urut'=>'EE002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pharmacy' ],
            ['menu_id'=>'EE003','group_menu'=>'penunjang','menu_title'=>'Hemodialisa','no_urut'=>'EE003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/hemo' ],
            ['menu_id'=>'EE004','group_menu'=>'penunjang','menu_title'=>'Fisiotherapi','no_urut'=>'EE004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/fisio' ],
            ['menu_id'=>'EE005','group_menu'=>'penunjang','menu_title'=>'Pathologi Anatomi','no_urut'=>'EE005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/patologi' ],
            ['menu_id'=>'EE006','group_menu'=>'penunjang','menu_title'=>'Ambulance','no_urut'=>'EE006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/ambulance' ],
            ['menu_id'=>'EE007','group_menu'=>'penunjang','menu_title'=>'Pemulasaraan Jenazah','no_urut'=>'EE007','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/penunjang/pemulasaraan' ],
            ['menu_id'=>'EE008','group_menu'=>'penunjang','menu_title'=>'Laboratorium','no_urut'=>'EE008','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/lab/pemeriksaan' ],
            ['menu_id'=>'EE009','group_menu'=>'penunjang','menu_title'=>'Radiologi','no_urut'=>'EE009','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/rad/pemeriksaan' ],

            ['menu_id'=>'FF000','group_menu'=>'persediaan','menu_title'=>'Manajemen Persediaan','no_urut'=>'FF000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'tag','menu_link'=>'persediaan' ],
            ['menu_id'=>'FF001','group_menu'=>'persediaan','menu_title'=>'Referensi Produk','no_urut'=>'FF001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/referensi' ],
            ['menu_id'=>'FF002','group_menu'=>'persediaan','menu_title'=>'Pemasok dan Pabrikan','no_urut'=>'FF002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/pemasok' ],
            ['menu_id'=>'FF003','group_menu'=>'persediaan','menu_title'=>'Item Persediaan','no_urut'=>'FF003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/produk' ],
            ['menu_id'=>'FF004','group_menu'=>'persediaan','menu_title'=>'Depo Persediaan','no_urut'=>'FF004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/depo' ],
            ['menu_id'=>'FF005','group_menu'=>'persediaan','menu_title'=>'Stock Opname','no_urut'=>'FF005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/opname' ],
            ['menu_id'=>'FF006','group_menu'=>'persediaan','menu_title'=>'Stock Adjustment','no_urut'=>'FF006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/penyesuaian' ],
            ['menu_id'=>'FF007','group_menu'=>'persediaan','menu_title'=>'Pengeluaran Persediaan','no_urut'=>'FF007','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/pengeluaran' ],
            ['menu_id'=>'FF008','group_menu'=>'persediaan','menu_title'=>'Produksi Persediaan','no_urut'=>'FF008','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/produksi' ],
            ['menu_id'=>'FF009','group_menu'=>'persediaan','menu_title'=>'Distribusi Persediaan','no_urut'=>'FF009','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/distribusi' ],
            ['menu_id'=>'FF010','group_menu'=>'persediaan','menu_title'=>'Purchase Request','no_urut'=>'FF010','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/permintaan' ],
            ['menu_id'=>'FF011','group_menu'=>'persediaan','menu_title'=>'Purchase Order','no_urut'=>'FF011','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/pembelian' ],
            ['menu_id'=>'FF012','group_menu'=>'persediaan','menu_title'=>'Purchase Order Receive','no_urut'=>'FF012','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/penerimaan' ],
            ['menu_id'=>'FF013','group_menu'=>'persediaan','menu_title'=>'Purchase Order Return','no_urut'=>'FF013','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/pengembalian' ],
            ['menu_id'=>'FF014','group_menu'=>'persediaan','menu_title'=>'Penerimaan Hibah','no_urut'=>'FF014','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/hibah' ],
            ['menu_id'=>'FF015','group_menu'=>'persediaan','menu_title'=>'Pembelian Langsung','no_urut'=>'FF015','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/belilangsung' ],
            ['menu_id'=>'FF016','group_menu'=>'persediaan','menu_title'=>'Pengelolaan Pengadaan','no_urut'=>'FF016','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/maintenance' ],
            ['menu_id'=>'FF017','group_menu'=>'persediaan','menu_title'=>'Pemusnahan','no_urut'=>'FF017','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/persediaan/pemusnahan' ],

            ['menu_id'=>'GG000','group_menu'=>'bankdarah','menu_title'=>'Bank Darah','no_urut'=>'GG000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'lifesaver','menu_link'=>'bankdarah' ],
            ['menu_id'=>'GG001','group_menu'=>'bankdarah','menu_title'=>'Referensi Bank Darah','no_urut'=>'GG001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/bankdarah/referensi' ],
            ['menu_id'=>'GG002','group_menu'=>'bankdarah','menu_title'=>'Informasi Persediaan Darah','no_urut'=>'GG002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/bankdarah/info' ],
            ['menu_id'=>'GG003','group_menu'=>'bankdarah','menu_title'=>'Penerimaan Persediaan Darah','no_urut'=>'GG003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/bankdarah/penerimaan' ],
            ['menu_id'=>'GG004','group_menu'=>'bankdarah','menu_title'=>'Permintaan dan Distribusi Darah','no_urut'=>'GG004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/bankdarah/permintaan' ],
            ['menu_id'=>'GG005','group_menu'=>'bankdarah','menu_title'=>'Pemusnahan Darah','no_urut'=>'GG005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/bankdarah/pemusnahan' ],
            ['menu_id'=>'GG006','group_menu'=>'bankdarah','menu_title'=>'Monitoring Transfusi Darah','no_urut'=>'GG006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/bankdarah/monitoring' ],

            ['menu_id'=>'HH000','group_menu'=>'laundry','menu_title'=>'Laundry dan Linen','no_urut'=>'HH000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'lifesaver','menu_link'=>'laundry' ],
            ['menu_id'=>'HH001','group_menu'=>'laundry','menu_title'=>'Informasi Persediaan Linen','no_urut'=>'HH001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/laundry/info' ],
            ['menu_id'=>'HH002','group_menu'=>'laundry','menu_title'=>'Penerimaan Linen','no_urut'=>'HH002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/laundry/penerimaan' ],
            ['menu_id'=>'HH003','group_menu'=>'laundry','menu_title'=>'Distribusi Linen','no_urut'=>'HH003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/laundry/pengiriman' ],
            ['menu_id'=>'HH004','group_menu'=>'laundry','menu_title'=>'Pemusnahan Linen','no_urut'=>'HH004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/laundry/pemusnahan' ],

            ['menu_id'=>'II000','group_menu'=>'cssd','menu_title'=>'CSSD','no_urut'=>'II000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'lifesaver','menu_link'=>'cssd' ],
            ['menu_id'=>'II001','group_menu'=>'cssd','menu_title'=>'Informasi Persediaan Item Steril','no_urut'=>'II001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/cssd/info' ],
            ['menu_id'=>'II002','group_menu'=>'cssd','menu_title'=>'Penerimaan Item Steril','no_urut'=>'II002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/cssd/penerimaan' ],
            ['menu_id'=>'II003','group_menu'=>'cssd','menu_title'=>'Distribusi Item Steril','no_urut'=>'II003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/cssd/pengiriman' ],
            ['menu_id'=>'II004','group_menu'=>'cssd','menu_title'=>'Pemusnahan Item Steril','no_urut'=>'II004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/cssd/pemusnahan' ],

            ['menu_id'=>'JJ000','group_menu'=>'gizi','menu_title'=>'Gizi dan Diet Pasien','no_urut'=>'JJ000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'lifesaver','menu_link'=>'gizi' ],
            ['menu_id'=>'JJ001','group_menu'=>'gizi','menu_title'=>'Referensi Gizi','no_urut'=>'JJ001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/gizi/referensi' ],
            ['menu_id'=>'JJ002','group_menu'=>'gizi','menu_title'=>'Makanan','no_urut'=>'JJ002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/makanan' ],
            ['menu_id'=>'JJ003','group_menu'=>'gizi','menu_title'=>'Diet','no_urut'=>'JJ003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/diet' ],
            ['menu_id'=>'JJ004','group_menu'=>'gizi','menu_title'=>'Kelompok Makanan','no_urut'=>'JJ004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/makanan' ],
            ['menu_id'=>'JJ005','group_menu'=>'gizi','menu_title'=>'Menu','no_urut'=>'JJ005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/menu' ],
            ['menu_id'=>'JJ006','group_menu'=>'gizi','menu_title'=>'Menu Makanan','no_urut'=>'JJ006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/mealsmenu' ],
            ['menu_id'=>'JJ007','group_menu'=>'gizi','menu_title'=>'Kelompok Menu','no_urut'=>'JJ007','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/menu' ],
            ['menu_id'=>'JJ008','group_menu'=>'gizi','menu_title'=>'Template Gizi','no_urut'=>'JJ008','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/template/gizi' ],
            ['menu_id'=>'JJ009','group_menu'=>'gizi','menu_title'=>'Distribusi Menu','no_urut'=>'JJ009','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/distribusi/gizi' ],
            // ['menu_id'=>'JJ010','group_menu'=>'gizi','menu_title'=>'Detail Distribusi Menu','no_urut'=>'JJ010','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/distribusi/detail/gizi' ],
            ['menu_id'=>'JJ010','group_menu'=>'gizi','menu_title'=>'Monitoring Gizi dan Diet','no_urut'=>'JJ010','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/gizi/monitoring' ],
            ['menu_id'=>'JJ011','group_menu'=>'gizi','menu_title'=>'Diet Pasien','no_urut'=>'JJ011','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/pasien/diet' ],
            ['menu_id'=>'JJ012','group_menu'=>'gizi','menu_title'=>'Meal Order','no_urut'=>'JJ012','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/mealorder' ],

            ['menu_id'=>'KK000','group_menu'=>'laboratorium','menu_title'=>'Laboratorium','no_urut'=>'KK000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'paint-bucket','menu_link'=>'laboratorium' ],
            ['menu_id'=>'KK001','group_menu'=>'laboratorium','menu_title'=>'Referensi Laboratorium','no_urut'=>'KK001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/lab/referensi' ],
            ['menu_id'=>'KK002','group_menu'=>'laboratorium','menu_title'=>'Master Item Hasil','no_urut'=>'KK002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/lab/master/item' ],
            ['menu_id'=>'KK003','group_menu'=>'laboratorium','menu_title'=>'Master Pemeriksaan','no_urut'=>'KK003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/lab/master/pemeriksaan' ],
            ['menu_id'=>'KK004','group_menu'=>'laboratorium','menu_title'=>'Template Hasil Lab','no_urut'=>'KK004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/lab/template' ],
            ['menu_id'=>'KK005','group_menu'=>'laboratorium','menu_title'=>'Pendaftaran Laboratorium','no_urut'=>'KK005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/lab/registrasi' ],
            ['menu_id'=>'KK006','group_menu'=>'laboratorium','menu_title'=>'Pemeriksaan Lab','no_urut'=>'KK006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/lab/pemeriksaan' ],

            ['menu_id'=>'LL000','group_menu'=>'radiologi','menu_title'=>'Radiologi','no_urut'=>'LL000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'image','menu_link'=>'radiologi' ],
            ['menu_id'=>'LL001','group_menu'=>'radiologi','menu_title'=>'Referensi Radiologi','no_urut'=>'LL001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/rad/referensi' ],
            ['menu_id'=>'LL002','group_menu'=>'radiologi','menu_title'=>'Master Pemeriksaan','no_urut'=>'LL002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/rad/master/pemeriksaan' ],
            ['menu_id'=>'LL003','group_menu'=>'radiologi','menu_title'=>'Template Hasil Radiologi','no_urut'=>'LL003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/rad/template' ],
            ['menu_id'=>'LL004','group_menu'=>'radiologi','menu_title'=>'Pendaftaran Radiologi','no_urut'=>'LL004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/rad/registrasi' ],
            ['menu_id'=>'LL005','group_menu'=>'radiologi','menu_title'=>'Pemeriksaan Radiologi','no_urut'=>'LL005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/rad/pemeriksaan' ],

            ['menu_id'=>'MM000','group_menu'=>'satusehat','menu_title'=>'Satu Sehat (IHS)','no_urut'=>'MM000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'album','menu_link'=>'/satusehat' ],
            ['menu_id'=>'MM001','group_menu'=>'satusehat','menu_title'=>'Practitioner Reference','no_urut'=>'MM001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/satusehat/practitioner' ],
            ['menu_id'=>'MM002','group_menu'=>'satusehat','menu_title'=>'Patient Reference','no_urut'=>'MM002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/satusehat/patient' ],
            ['menu_id'=>'MM003','group_menu'=>'satusehat','menu_title'=>'Organization','no_urut'=>'MM003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/satusehat/organization' ],
            ['menu_id'=>'MM004','group_menu'=>'satusehat','menu_title'=>'Location','no_urut'=>'MM004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/satusehat/location' ],

            ['menu_id'=>'YY000','group_menu'=>'masterdata','menu_title'=>'Master Data','no_urut'=>'YY000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'database','menu_link'=>'' ],
            ['menu_id'=>'YY001','group_menu'=>'masterdata','menu_title'=>'Referensi Aplikasi','no_urut'=>'YY001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/referensi' ],
            ['menu_id'=>'YY002','group_menu'=>'masterdata','menu_title'=>'Kelompok Tindakan','no_urut'=>'YY002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelompok/tindakan' ],
            ['menu_id'=>'YY003','group_menu'=>'masterdata','menu_title'=>'Tindakan dan pemeriksaan','no_urut'=>'YY003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/tindakan' ],
            ['menu_id'=>'YY004','group_menu'=>'masterdata','menu_title'=>'Kode Laporan RL','no_urut'=>'YY004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/rl' ],
            ['menu_id'=>'YY005','group_menu'=>'masterdata','menu_title'=>'Wilayah','no_urut'=>'YY005','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/wilayah' ],
            ['menu_id'=>'YY006','group_menu'=>'masterdata','menu_title'=>'Kode ICD','no_urut'=>'YY006','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/icd' ],
            ['menu_id'=>'YY007','group_menu'=>'masterdata','menu_title'=>'Pasien','no_urut'=>'YY007','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/pasien' ],
            ['menu_id'=>'YY008','group_menu'=>'masterdata','menu_title'=>'Signa Obat','no_urut'=>'YY008','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/signa' ],
            ['menu_id'=>'YY009','group_menu'=>'masterdata','menu_title'=>'KSM-Kelompok Staf Medis','no_urut'=>'YY009','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/ksm' ],
            ['menu_id'=>'YY010','group_menu'=>'masterdata','menu_title'=>'Dokter dan Spesialis','no_urut'=>'YY010','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/dokter' ],
            ['menu_id'=>'YY011','group_menu'=>'masterdata','menu_title'=>'Kelas Pelayanan','no_urut'=>'YY011','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/kelas' ],
            ['menu_id'=>'YY012','group_menu'=>'masterdata','menu_title'=>'Unit Pelayanan','no_urut'=>'YY012','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/unit/pelayanan' ],
            ['menu_id'=>'YY013','group_menu'=>'masterdata','menu_title'=>'Ruang dan Bed','no_urut'=>'YY013','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/ruang' ],
            ['menu_id'=>'YY014','group_menu'=>'masterdata','menu_title'=>'Jadwal Praktek Dokter','no_urut'=>'YY014','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/master/jadwal/dokter' ],
            ['menu_id'=>'YY015','group_menu'=>'masterdata','menu_title'=>'Template Hasil Radiologi','no_urut'=>'YY015','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/template/rad' ],
            ['menu_id'=>'YY016','group_menu'=>'masterdata','menu_title'=>'Template Hasil Lab','no_urut'=>'YY016','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/template/lab' ],
            ['menu_id'=>'YY017','group_menu'=>'masterdata','menu_title'=>'Item Hasil Laboratorium','no_urut'=>'YY017','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/itemlab' ],
            ['menu_id'=>'YY018','group_menu'=>'masterdata','menu_title'=>'Makanan','no_urut'=>'YY018','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/makanan' ],
            ['menu_id'=>'YY019','group_menu'=>'masterdata','menu_title'=>'Diet Pasien','no_urut'=>'YY019','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/diet' ],
            ['menu_id'=>'YY020','group_menu'=>'masterdata','menu_title'=>'Item Medis','no_urut'=>'YY020','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/produk/medis' ],
            ['menu_id'=>'YY021','group_menu'=>'masterdata','menu_title'=>'Item Non Medis ','no_urut'=>'YY021','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/produk/umum' ],
            ['menu_id'=>'YY022','group_menu'=>'masterdata','menu_title'=>'Item Dapur','no_urut'=>'YY022','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/produk/dapur' ],
            ['menu_id'=>'YY023','group_menu'=>'masterdata','menu_title'=>'Depo Persediaan','no_urut'=>'YY023','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/depo' ],
            ['menu_id'=>'YY024','group_menu'=>'masterdata','menu_title'=>'DTD dan Diagnosa','no_urut'=>'YY024','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/dtd' ],
            ['menu_id'=>'YY025','group_menu'=>'masterdata','menu_title'=>'Spesialisasi Dokter','no_urut'=>'YY025','is_nav_header'=>FALSE,'is_aktif'=>FALSE,'menu_icon'=>'','menu_link'=>'/master/spesialisasi' ],

            ['menu_id'=>'XX000','group_menu'=>'report','menu_title'=>'Report','no_urut'=>'XX000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'pdf','menu_link'=>'' ],
            ['menu_id'=>'XX001','group_menu'=>'report','menu_title'=>'List Report','no_urut'=>'XX001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/report' ],
        
            ['menu_id'=>'ZZ000','group_menu'=>'asset','menu_title'=>'Asset','no_urut'=>'ZZ000','is_nav_header'=>TRUE,'is_aktif'=>TRUE,'menu_icon'=>'pdf','menu_link'=>'' ],
            ['menu_id'=>'ZZ001','group_menu'=>'asset','menu_title'=>'Master Asset','no_urut'=>'ZZ001','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/asset' ],
            ['menu_id'=>'ZZ002','group_menu'=>'asset','menu_title'=>'Asset Overview','no_urut'=>'ZZ002','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/asset/overview' ],
            ['menu_id'=>'ZZ003','group_menu'=>'asset','menu_title'=>'Maintenance','no_urut'=>'ZZ003','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'pdf','menu_link'=>'' ],
            ['menu_id'=>'ZZ004','group_menu'=>'asset','menu_title'=>'Maintenance Ticket','no_urut'=>'ZZ004','is_nav_header'=>FALSE,'is_aktif'=>TRUE,'menu_icon'=>'','menu_link'=>'/asset/maintenance' ],
        ]);
    }
}
